<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>KARider.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\KARider.Domain\KARider.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.19" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.19" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="9.0.19" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="KARider.UnitTests" />
  </ItemGroup>

</Project>
