// <auto-generated />
using System;
using System.Collections.Generic;
using KARider.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KARider.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KARider.Domain.Entities.Calificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("Comentario")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("comentario");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<int>("Estrellas")
                        .HasColumnType("integer")
                        .HasColumnName("estrellas");

                    b.PrimitiveCollection<List<string>>("Etiquetas")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("etiquetas");

                    b.Property<Guid>("EvaluadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("evaluado_id");

                    b.Property<Guid>("EvaluadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("evaluador_id");

                    b.Property<string>("RolEvaluado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("rol_evaluado");

                    b.Property<Guid>("ViajeId")
                        .HasColumnType("uuid")
                        .HasColumnName("viaje_id");

                    b.HasKey("Id")
                        .HasName("pk_calificaciones");

                    b.HasIndex("EvaluadorId")
                        .HasDatabaseName("ix_calificaciones_evaluador_id");

                    b.HasIndex("EvaluadoId", "CreadoEn")
                        .HasDatabaseName("ix_calificaciones_evaluado_id_creado_en");

                    b.HasIndex("ViajeId", "EvaluadorId", "EvaluadoId")
                        .IsUnique()
                        .HasDatabaseName("ix_calificaciones_viaje_id_evaluador_id_evaluado_id");

                    b.ToTable("calificaciones", null, t =>
                        {
                            t.HasCheckConstraint("ck_calificaciones_estrellas", "estrellas BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("KARider.Domain.Entities.Carrera", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_carreras");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_carreras_nombre");

                    b.ToTable("carreras", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            Nombre = "Ingeniería en Desarrollo y Gestión de Software"
                        },
                        new
                        {
                            Id = 2,
                            Activa = true,
                            Nombre = "Ingeniería en Mecatrónica"
                        },
                        new
                        {
                            Id = 3,
                            Activa = true,
                            Nombre = "Ingeniería en Tecnologías de la Información e Innovación Digital"
                        },
                        new
                        {
                            Id = 4,
                            Activa = true,
                            Nombre = "Ingeniería en Mantenimiento Industrial"
                        },
                        new
                        {
                            Id = 5,
                            Activa = true,
                            Nombre = "Ingeniería en Procesos y Operaciones Industriales"
                        },
                        new
                        {
                            Id = 6,
                            Activa = true,
                            Nombre = "Ingeniería en Energías Renovables"
                        },
                        new
                        {
                            Id = 7,
                            Activa = true,
                            Nombre = "Ingeniería Química"
                        },
                        new
                        {
                            Id = 8,
                            Activa = true,
                            Nombre = "Ingeniería en Logística Internacional"
                        },
                        new
                        {
                            Id = 9,
                            Activa = true,
                            Nombre = "Ingeniería Civil"
                        },
                        new
                        {
                            Id = 10,
                            Activa = true,
                            Nombre = "Licenciatura en Contaduría"
                        },
                        new
                        {
                            Id = 11,
                            Activa = true,
                            Nombre = "Licenciatura en Negocios y Mercadotecnia"
                        },
                        new
                        {
                            Id = 12,
                            Activa = true,
                            Nombre = "Licenciatura en Administración"
                        });
                });

            modelBuilder.Entity("KARider.Domain.Entities.CodigoVerificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("CodigoHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("codigo_hash");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<DateTimeOffset>("ExpiraEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_en");

                    b.Property<int>("Intentos")
                        .HasColumnType("integer")
                        .HasColumnName("intentos");

                    b.Property<string>("Proposito")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("proposito");

                    b.Property<DateTimeOffset?>("UsadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usado_en");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_codigos_verificacion");

                    b.HasIndex("UsuarioId", "Proposito", "CreadoEn")
                        .HasDatabaseName("ix_codigos_verificacion_usuario_id_proposito_creado_en");

                    b.ToTable("codigos_verificacion", (string)null);
                });

            modelBuilder.Entity("KARider.Domain.Entities.Notificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<bool>("Leida")
                        .HasColumnType("boolean")
                        .HasColumnName("leida");

                    b.Property<DateTimeOffset?>("LeidaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("leida_en");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)")
                        .HasColumnName("mensaje");

                    b.Property<Guid?>("ReservaId")
                        .HasColumnType("uuid")
                        .HasColumnName("reserva_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("titulo");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<Guid?>("ViajeId")
                        .HasColumnType("uuid")
                        .HasColumnName("viaje_id");

                    b.HasKey("Id")
                        .HasName("pk_notificaciones");

                    b.HasIndex("UsuarioId", "Leida", "CreadoEn")
                        .HasDatabaseName("ix_notificaciones_usuario_id_leida_creado_en");

                    b.ToTable("notificaciones", (string)null);
                });

            modelBuilder.Entity("KARider.Domain.Entities.ParadaViaje", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<Guid>("ViajeId")
                        .HasColumnType("uuid")
                        .HasColumnName("viaje_id");

                    b.HasKey("Id")
                        .HasName("pk_paradas_viaje");

                    b.HasIndex("ViajeId", "Orden")
                        .IsUnique()
                        .HasDatabaseName("ix_paradas_viaje_viaje_id_orden");

                    b.ToTable("paradas_viaje", (string)null);
                });

            modelBuilder.Entity("KARider.Domain.Entities.PuntoEncuentro", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descripcion");

                    b.Property<double>("Latitud")
                        .HasColumnType("double precision")
                        .HasColumnName("latitud");

                    b.Property<double>("Longitud")
                        .HasColumnType("double precision")
                        .HasColumnName("longitud");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_puntos_encuentro");

                    b.ToTable("puntos_encuentro", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Junto a la caseta de vigilancia, frente a los torniquetes de acceso peatonal.",
                            Latitud = 20.087499999999999,
                            Longitud = -99.347999999999999,
                            Nombre = "Puerta Principal (Torniquetes Acceso A)"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Explanada frente al Edificio B, área de Desarrollo y Gestión de Software.",
                            Latitud = 20.088100000000001,
                            Longitud = -99.347200000000001,
                            Nombre = "Edificio B (Explanada de Sistemas · IDGS)"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Entrada vehicular del estacionamiento principal del campus.",
                            Latitud = 20.087,
                            Longitud = -99.3489,
                            Nombre = "Estacionamiento principal"
                        });
                });

            modelBuilder.Entity("KARider.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<DateTimeOffset>("ExpiraEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_en");

                    b.Property<string>("IpCreacion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_creacion");

                    b.Property<bool>("Recordarme")
                        .HasColumnType("boolean")
                        .HasColumnName("recordarme");

                    b.Property<Guid?>("ReemplazadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("reemplazado_por_id");

                    b.Property<DateTimeOffset?>("RevocadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revocado_en");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UsuarioId", "RevocadoEn")
                        .HasDatabaseName("ix_refresh_tokens_usuario_id_revocado_en");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("KARider.Domain.Entities.Reserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<bool>("AportePagado")
                        .HasColumnType("boolean")
                        .HasColumnName("aporte_pagado");

                    b.Property<int>("Asientos")
                        .HasColumnType("integer")
                        .HasColumnName("asientos");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("folio");

                    b.Property<decimal>("MontoAporte")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("monto_aporte");

                    b.Property<Guid>("PasajeroId")
                        .HasColumnType("uuid")
                        .HasColumnName("pasajero_id");

                    b.Property<DateTimeOffset?>("RespondidaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("respondida_en");

                    b.Property<Guid>("ViajeId")
                        .HasColumnType("uuid")
                        .HasColumnName("viaje_id");

                    b.HasKey("Id")
                        .HasName("pk_reservas");

                    b.HasIndex("Folio")
                        .IsUnique()
                        .HasDatabaseName("ix_reservas_folio");

                    b.HasIndex("PasajeroId", "Estado")
                        .HasDatabaseName("ix_reservas_pasajero_id_estado");

                    b.HasIndex("ViajeId", "PasajeroId")
                        .IsUnique()
                        .HasDatabaseName("ix_reservas_viaje_id_pasajero_id")
                        .HasFilter("estado IN ('Pendiente', 'Confirmada')");

                    b.ToTable("reservas", null, t =>
                        {
                            t.HasCheckConstraint("ck_reservas_asientos", "asientos BETWEEN 1 AND 2");
                        });
                });

            modelBuilder.Entity("KARider.Domain.Entities.SuscripcionPush", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("auth");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("endpoint");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("p256dh");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_suscripciones_push");

                    b.HasIndex("Endpoint")
                        .IsUnique()
                        .HasDatabaseName("ix_suscripciones_push_endpoint");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_suscripciones_push_usuario_id");

                    b.ToTable("suscripciones_push", (string)null);
                });

            modelBuilder.Entity("KARider.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTimeOffset?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTimeOffset?>("BloqueadoHasta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bloqueado_hasta");

                    b.Property<decimal>("CalificacionPromedio")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("calificacion_promedio");

                    b.Property<int>("CarreraId")
                        .HasColumnType("integer")
                        .HasColumnName("carrera_id");

                    b.Property<string>("CorreoInstitucional")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("correo_institucional");

                    b.Property<bool>("CorreoVerificado")
                        .HasColumnType("boolean")
                        .HasColumnName("correo_verificado");

                    b.Property<DateTimeOffset?>("CorreoVerificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("correo_verificado_en");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<int?>("Cuatrimestre")
                        .HasColumnType("integer")
                        .HasColumnName("cuatrimestre");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("foto_url");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("integer")
                        .HasColumnName("intentos_fallidos");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("matricula");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("rol");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("security_stamp");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.Property<int>("TotalCalificaciones")
                        .HasColumnType("integer")
                        .HasColumnName("total_calificaciones");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("CarreraId")
                        .HasDatabaseName("ix_usuarios_carrera_id");

                    b.HasIndex("CorreoInstitucional")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_correo_institucional");

                    b.HasIndex("Matricula")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_matricula");

                    b.ToTable("usuarios", null, t =>
                        {
                            t.HasCheckConstraint("ck_usuarios_calificacion", "calificacion_promedio BETWEEN 0 AND 5");

                            t.HasCheckConstraint("ck_usuarios_cuatrimestre", "cuatrimestre IS NULL OR cuatrimestre BETWEEN 1 AND 11");
                        });
                });

            modelBuilder.Entity("KARider.Domain.Entities.Vehiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTimeOffset?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<int>("Anio")
                        .HasColumnType("integer")
                        .HasColumnName("anio");

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer")
                        .HasColumnName("capacidad");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("color");

                    b.Property<Guid>("ConductorId")
                        .HasColumnType("uuid")
                        .HasColumnName("conductor_id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("modelo");

                    b.Property<string>("Placas")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("placas");

                    b.Property<bool>("Verificado")
                        .HasColumnType("boolean")
                        .HasColumnName("verificado");

                    b.HasKey("Id")
                        .HasName("pk_vehiculos");

                    b.HasIndex("ConductorId")
                        .HasDatabaseName("ix_vehiculos_conductor_id");

                    b.HasIndex("Placas")
                        .IsUnique()
                        .HasDatabaseName("ix_vehiculos_placas")
                        .HasFilter("activo = true");

                    b.ToTable("vehiculos", null, t =>
                        {
                            t.HasCheckConstraint("ck_vehiculos_capacidad", "capacidad BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("KARider.Domain.Entities.Viaje", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<decimal>("AportePorAsiento")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("aporte_por_asiento");

                    b.Property<int>("AsientosDisponibles")
                        .HasColumnType("integer")
                        .HasColumnName("asientos_disponibles");

                    b.Property<int>("AsientosOfrecidos")
                        .HasColumnType("integer")
                        .HasColumnName("asientos_ofrecidos");

                    b.Property<Guid>("ConductorId")
                        .HasColumnType("uuid")
                        .HasColumnName("conductor_id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("destino");

                    b.Property<double?>("DestinoLatitud")
                        .HasColumnType("double precision")
                        .HasColumnName("destino_latitud");

                    b.Property<double?>("DestinoLongitud")
                        .HasColumnType("double precision")
                        .HasColumnName("destino_longitud");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("FechaSalida")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_salida");

                    b.Property<decimal>("GastoTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("gasto_total");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notas");

                    b.Property<int>("PuntoEncuentroId")
                        .HasColumnType("integer")
                        .HasColumnName("punto_encuentro_id");

                    b.Property<DateTimeOffset?>("UbicacionActualizadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ubicacion_actualizada_en");

                    b.Property<double?>("UbicacionLatitud")
                        .HasColumnType("double precision")
                        .HasColumnName("ubicacion_latitud");

                    b.Property<double?>("UbicacionLongitud")
                        .HasColumnType("double precision")
                        .HasColumnName("ubicacion_longitud");

                    b.Property<Guid>("VehiculoId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehiculo_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_viajes");

                    b.HasIndex("PuntoEncuentroId")
                        .HasDatabaseName("ix_viajes_punto_encuentro_id");

                    b.HasIndex("VehiculoId")
                        .HasDatabaseName("ix_viajes_vehiculo_id");

                    b.HasIndex("ConductorId", "FechaSalida")
                        .HasDatabaseName("ix_viajes_conductor_id_fecha_salida");

                    b.HasIndex("Estado", "FechaSalida")
                        .HasDatabaseName("ix_viajes_estado_fecha_salida");

                    b.ToTable("viajes", null, t =>
                        {
                            t.HasCheckConstraint("ck_viajes_asientos", "asientos_disponibles >= 0 AND asientos_disponibles <= asientos_ofrecidos");

                            t.HasCheckConstraint("ck_viajes_gasto", "gasto_total > 0");
                        });
                });

            modelBuilder.Entity("KARider.Domain.Entities.Calificacion", b =>
                {
                    b.HasOne("KARider.Domain.Entities.Usuario", "Evaluado")
                        .WithMany()
                        .HasForeignKey("EvaluadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_calificaciones_usuarios_evaluado_id");

                    b.HasOne("KARider.Domain.Entities.Usuario", "Evaluador")
                        .WithMany()
                        .HasForeignKey("EvaluadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_calificaciones_usuarios_evaluador_id");

                    b.HasOne("KARider.Domain.Entities.Viaje", "Viaje")
                        .WithMany()
                        .HasForeignKey("ViajeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_calificaciones_viajes_viaje_id");

                    b.Navigation("Evaluado");

                    b.Navigation("Evaluador");

                    b.Navigation("Viaje");
                });

            modelBuilder.Entity("KARider.Domain.Entities.CodigoVerificacion", b =>
                {
                    b.HasOne("KARider.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_codigos_verificacion_usuarios_usuario_id");
                });

            modelBuilder.Entity("KARider.Domain.Entities.Notificacion", b =>
                {
                    b.HasOne("KARider.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notificaciones_usuarios_usuario_id");
                });

            modelBuilder.Entity("KARider.Domain.Entities.ParadaViaje", b =>
                {
                    b.HasOne("KARider.Domain.Entities.Viaje", null)
                        .WithMany("Paradas")
                        .HasForeignKey("ViajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_paradas_viaje_viajes_viaje_id");
                });

            modelBuilder.Entity("KARider.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("KARider.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_usuarios_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("KARider.Domain.Entities.Reserva", b =>
                {
                    b.HasOne("KARider.Domain.Entities.Usuario", "Pasajero")
                        .WithMany()
                        .HasForeignKey("PasajeroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reservas_usuarios_pasajero_id");

                    b.HasOne("KARider.Domain.Entities.Viaje", "Viaje")
                        .WithMany("Reservas")
                        .HasForeignKey("ViajeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reservas_viajes_viaje_id");

                    b.Navigation("Pasajero");

                    b.Navigation("Viaje");
                });

            modelBuilder.Entity("KARider.Domain.Entities.SuscripcionPush", b =>
                {
                    b.HasOne("KARider.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_suscripciones_push_usuarios_usuario_id");
                });

            modelBuilder.Entity("KARider.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("KARider.Domain.Entities.Carrera", "Carrera")
                        .WithMany()
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_carreras_carrera_id");

                    b.Navigation("Carrera");
                });

            modelBuilder.Entity("KARider.Domain.Entities.Vehiculo", b =>
                {
                    b.HasOne("KARider.Domain.Entities.Usuario", "Conductor")
                        .WithMany("Vehiculos")
                        .HasForeignKey("ConductorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vehiculos_usuarios_conductor_id");

                    b.Navigation("Conductor");
                });

            modelBuilder.Entity("KARider.Domain.Entities.Viaje", b =>
                {
                    b.HasOne("KARider.Domain.Entities.Usuario", "Conductor")
                        .WithMany()
                        .HasForeignKey("ConductorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_viajes_usuarios_conductor_id");

                    b.HasOne("KARider.Domain.Entities.PuntoEncuentro", "PuntoEncuentro")
                        .WithMany()
                        .HasForeignKey("PuntoEncuentroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_viajes_puntos_encuentro_punto_encuentro_id");

                    b.HasOne("KARider.Domain.Entities.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_viajes_vehiculos_vehiculo_id");

                    b.Navigation("Conductor");

                    b.Navigation("PuntoEncuentro");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("KARider.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("KARider.Domain.Entities.Viaje", b =>
                {
                    b.Navigation("Paradas");

                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
